import type { LessonChunk } from "../types";

/** Lab 08 — Dead Letter Queue & Failure Recovery. Condensed from the lab README. */
export const LAB_08_CHUNKS: readonly LessonChunk[] = [
  {
    kind: "problem",
    id: "problem",
    title: "Keep the failures you still need to fix",
    content: [
      {
        type: "prose",
        text: "Three retries. Three failures. The downstream service is not coming back this afternoon.",
      },
      {
        type: "prose",
        text: "Your workflow does the only thing it knows how to do: it stops. And the customer's order — the thing this automation existed to handle — is now gone. Not delayed. Gone.",
      },
      {
        type: "prose",
        text: "Retries handle failures that end. Some do not: a service down for hours, a credential that expired overnight. When retries run out the work has to go somewhere, or you find out it was lost when a customer asks why nothing happened.",
      },
    ],
  },
  {
    kind: "concept",
    id: "concept",
    title: "Save it, investigate it, replay it",
    content: [
      {
        type: "prose",
        text: "What is it? A Dead Letter Queue is a safe place for events that normal processing could not recover. The event is not deleted — it is preserved so someone can inspect it or replay it later.",
      },
      {
        type: "prose",
        text: "What problem does it solve? After retries are exhausted, a workflow without a DLQ has two options: stop and lose the work, or loop forever. A DLQ adds a third.",
      },
      {
        type: "prose",
        text: "How does this help a real business? Orders, payments and CRM syncs survive outages. The difference between a fragile system and a resilient one is not that the resilient one never fails — it is that failed work is still there in the morning.",
      },
      {
        type: "diagram",
        ascii: [
          "Event -> Process -> fail -> retry -> fail -> retry -> fail",
          "                                                     |",
          "                                          retries exhausted",
          "                                                     |",
          "                                               Save to DLQ",
          "",
          "Later:  Fetch pending -> Replay -> succeeded? -> mark recovered",
          "                                          \\-> stays pending",
        ].join("\n"),
        alt: "An event fails and retries until attempts are exhausted, then is saved to the dead letter queue. Later a recovery flow fetches it, replays it, and marks it recovered only if the replay succeeded; otherwise it stays pending.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-retry",
    title: "Build: process, and retry until the limit",
    whyThisMatters: [
      {
        type: "prose",
        text: "A DLQ is what happens after normal recovery has failed. So the retries come first: an event that would have succeeded on attempt three must never reach the queue.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Create the queue table in the Supabase SQL Editor.",
        code: {
          language: "sql",
          code: [
            "create table if not exists dlq_events (",
            "  id               bigint generated by default as identity primary key,",
            "  event_id         text not null,",
            "  event_type       text not null,",
            "  original_payload jsonb not null,",
            "  error_message    text not null,",
            "  retry_count      integer not null default 0,",
            "  first_failed_at  timestamptz not null default now(),",
            "  last_failed_at   timestamptz not null default now(),",
            "  status           text not null default 'pending',",
            "  recovered_at     timestamptz",
            ");",
          ].join("\n"),
        },
      },
      {
        text: "Add a Webhook named Receive Service Event (POST, path aep-lab-08-dlq, Respond: Using Respond to Webhook node), then two Code nodes: Prepare Processing Attempt, set to Run Once for Each Item, and Simulate Downstream Processing, which fails on demand so the lab does not depend on a genuinely broken service.",
        code: [
          {
            caption: "Prepare Processing Attempt",
            language: "javascript",
            code: [
              "const body = $json.body;",
              "",
              "return {",
              "  json: {",
              "    event_id: body.event_id,",
              "    event_type: body.event_type,",
              "    scenario: body.scenario,",
              "    max_attempts: body.max_attempts ?? 3,",
              "    success_on_attempt: body.success_on_attempt ?? 3,",
              "    attempt: 1,",
              "    first_failed_at: null,",
              "    original_payload: body",
              "  }",
              "};",
            ].join("\n"),
          },
          {
            caption: "Simulate Downstream Processing",
            language: "javascript",
            code: [
              "const scenario = $json.scenario;",
              "const attempt = $json.attempt;",
              "const successOnAttempt = $json.success_on_attempt;",
              "",
              "let success = false;",
              "let statusCode;",
              "let errorMessage = null;",
              "",
              "if (scenario === 'permanent_failure') {",
              "  statusCode = 503;",
              "  errorMessage = 'Downstream service unavailable';",
              "} else if (scenario === 'eventual_success') {",
              "  if (attempt >= successOnAttempt) {",
              "    success = true;",
              "    statusCode = 200;",
              "  } else {",
              "    statusCode = 503;",
              "    errorMessage = 'Temporary downstream failure';",
              "  }",
              "} else {",
              "  success = true;",
              "  statusCode = 200;",
              "}",
              "",
              "return {",
              "  json: {",
              "    ...$json,",
              "    processing_result: {",
              "      success,",
              "      status_code: statusCode,",
              "      error_message: errorMessage",
              "    }",
              "  }",
              "};",
            ].join("\n"),
          },
        ],
      },
      {
        text: "Add an IF named Processing Successful? with the Boolean condition {{ $json.processing_result.success }} is true. On true, add a Respond to Webhook named Return Processing Success: Respond With JSON, Response Code 200, and this Response Body in Expression mode. On false, add an IF named Retry Allowed? with the Boolean condition {{ $json.attempt < $json.max_attempts }} is true.",
        code: {
          language: "json",
          code: [
            "{",
            "  \"success\": true,",
            "  \"queued_for_recovery\": false,",
            "  \"message\": \"Event processed successfully\",",
            "  \"event_id\": \"{{$json.event_id}}\",",
            "  \"attempts_used\": {{$json.attempt}}",
            "}",
          ].join("\n"),
        },
      },
      {
        text: "On true, add a Code node named Increase Retry Count, set to Run Once for Each Item, and connect it back into Simulate Downstream Processing.",
        code: {
          language: "javascript",
          code: [
            "return {",
            "  json: {",
            "    ...$json,",
            "    attempt: $json.attempt + 1,",
            "    first_failed_at: $json.first_failed_at ?? new Date().toISOString()",
            "  }",
            "};",
          ].join("\n"),
        },
        expect: "A permanent failure tries three times, then Retry Allowed? goes false.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "original_payload is the most important column in the table. Knowing an event failed is not enough to recover it; you need the event itself, because the sender may no longer have it.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-queue",
    title: "Build: preserve the failure",
    whyThisMatters: [
      {
        type: "prose",
        text: "When Retry Allowed? goes false, the workflow has given up — for now. What it saves in the next few seconds decides whether anyone can ever recover this event.",
      },
    ],
    content: [],
    actions: [
      {
        text: "On false, add a Code node named Build DLQ Record that captures everything a recovery would need.",
        code: {
          language: "javascript",
          code: [
            "const now = new Date().toISOString();",
            "",
            "return {",
            "  json: {",
            "    event_id: $json.event_id,",
            "    event_type: $json.event_type,",
            "    original_payload: $json.original_payload,",
            "    error_message: $json.processing_result.error_message,",
            "    retry_count: $json.attempt,",
            "    first_failed_at: $json.first_failed_at ?? now,",
            "    last_failed_at: now,",
            "    status: 'pending'",
            "  }",
            "};",
          ].join("\n"),
        },
      },
      {
        text: "Add a Supabase node named Save to DLQ: Operation Create in dlq_events, mapping event_id, event_type, original_payload, error_message, retry_count, first_failed_at, last_failed_at and status from Build DLQ Record.",
      },
      {
        text: "Add a Respond to Webhook named Return Queued for Recovery: Respond With JSON, Response Code 200, and this Response Body in Expression mode.",
        code: {
          language: "json",
          code: [
            "{",
            "  \"success\": false,",
            "  \"queued_for_recovery\": true,",
            "  \"message\": \"Event moved to dead letter queue\",",
            "  \"event_id\": \"{{$json.event_id}}\",",
            "  \"retry_count\": {{$json.retry_count}},",
            "  \"status\": \"{{$json.status}}\"",
            "}",
          ].join("\n"),
        },
        expect: "success: false and queued_for_recovery: true in the same response.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "success: false with queued_for_recovery: true says two honest things at once: processing did not succeed, and the event was not lost. Collapsing them into one boolean would hide whichever one the caller needed.",
      },
    ],
    teaches: [
      {
        subject: "code",
        name: "Building the dead letter record",
        language: "javascript",
        code: "retry_count: $json.attempt,\noriginal_payload: $json.original_payload,\nstatus: 'pending'",
        intent: "Capture everything someone would need to understand and replay this failure later.",
        inputs: "The processing state at the moment retries were exhausted: the event, its original payload, the last error and the attempt count.",
        logic:
          "It selects the recovery-relevant fields rather than dumping the whole working state, and stamps the record pending so a recovery flow can find it.",
        output: "One clean row: what failed, why, after how many attempts, and the payload needed to try again.",
        engineeringReason:
          "A DLQ that stores only an error message tells you something failed and leaves you unable to fix it. The payload is what turns a failure report into recoverable work.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-recovery",
    title: "Build: replay it later — honestly",
    whyThisMatters: [
      {
        type: "prose",
        text: "Saving failures is half the job. The other half is getting them back out, and marking them recovered only when they actually were.",
      },
    ],
    content: [],
    actions: [
      {
        text: "In a separate flow, add a Manual Trigger named Start DLQ Recovery and an Edit Fields node named Set Recovery Config with dlq_id (Number) and recovery_scenario (String: success or failure).",
        expect: "Use the id of YOUR row — Postgres assigns ids in insert order.",
      },
      {
        text: "Add a Supabase node named Fetch Pending DLQ Event: Operation Get in dlq_events, with BOTH conditions id equals {{ $json.dlq_id }} and status equals pending.",
      },
      {
        text: "Add two Code nodes, Prepare Replay Payload (Run Once for Each Item) and Simulate Recovery Processing, then an IF named Recovery Successful? with the Boolean condition {{ $json.recovery_result.success }} is true.",
        code: [
          {
            caption: "Prepare Replay Payload",
            language: "javascript",
            code: [
              "const recoveryConfig = $('Set Recovery Config').item.json;",
              "",
              "return {",
              "  json: {",
              "    dlq_id: $json.id,",
              "    event_id: $json.event_id,",
              "    event_type: $json.event_type,",
              "    original_payload: $json.original_payload,",
              "    replay_payload: $json.original_payload,",
              "    recovery_attempts: ($json.recovery_attempts ?? 0) + 1,",
              "    recovery_scenario: recoveryConfig.recovery_scenario",
              "  }",
              "};",
            ].join("\n"),
          },
          {
            caption: "Simulate Recovery Processing",
            language: "javascript",
            code: [
              "const recoveryScenario =",
              "  $('Prepare Replay Payload').item.json.recovery_scenario;",
              "",
              "const success = recoveryScenario === 'success';",
              "",
              "return {",
              "  json: {",
              "    ...$json,",
              "    recovery_result: {",
              "      success,",
              "      status_code: success ? 200 : 503,",
              "      error_message: success ? null : 'Recovery attempt failed'",
              "    }",
              "  }",
              "};",
            ].join("\n"),
          },
        ],
      },
      {
        text: "On true, add a Supabase node named Mark DLQ Recovered: Operation Update in dlq_events where id equals {{ $json.dlq_id }}, setting status to recovered and recovered_at to {{ $now }}. On false, add a Code node named Keep DLQ Pending.",
        code: {
          language: "javascript",
          code: [
            "return {",
            "  json: {",
            "    dlq_id: $json.dlq_id,",
            "    event_id: $json.event_id,",
            "    recovery_success: false,",
            "    status: 'pending',",
            "    error_message: $json.recovery_result.error_message",
            "  }",
            "};",
          ].join("\n"),
        },
        expect: "A failed replay leaves the row pending.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "The status = pending filter is doing real work: an already-recovered event cannot be fetched and replayed again.",
      },
    ],
  },
  {
    kind: "predict",
    id: "predict",
    title: "Before you run it",
    content: [
      {
        type: "prose",
        text: "You have two samples: one that fails permanently, and one that fails twice and succeeds on the third attempt.",
      },
    ],
    prompt: "Which of them should end up in dlq_events?",
    reveal: [
      {
        type: "prose",
        text: "Only the permanent failure. The eventual-success event recovers inside its retries and finishes normally, so it has no business in a dead letter queue. A DLQ full of events that actually succeeded is noise that buries the ones that did not.",
      },
    ],
  },
  {
    kind: "test",
    id: "success-test",
    title: "Prove it",
    mode: "send-test",
    testCaseId: "lab-08-queued-for-recovery",
    payload: { event_id: "evt_dlq_001", event_type: "lead.sync", scenario: "permanent_failure", max_attempts: 3, data: { lead_id: "lead_301", name: "DLQ Test Lead", email: "dlq@example.com" } },
    expected: "success is false, but the event is queued for recovery after all 3 attempts — not lost.",
    caseName: "An event that fails permanently is preserved for recovery instead of being lost",
    content: [
      {
        type: "prose",
        text: "Publish your workflow in n8n (older versions call this switching it to Active), save its Production URL below, then send the test. AEP posts this lab's sample request to your own n8n and checks what your workflow answers. This event fails on every attempt, by design.",
      },
    ],
  },
  {
    kind: "break-it",
    id: "break-it",
    title: "Now break it on purpose",
    content: [
      {
        type: "actions",
        items: [
          {
            text: "In the recovery flow, bypass Recovery Successful? by connecting Simulate Recovery Processing straight to Mark DLQ Recovered.",
          },
          {
            text: "Run recovery on a pending row with recovery_scenario set to failure.",
          },
          {
            text: "Look at the row in dlq_events.",
            expect: "status recovered, recovered_at populated — for a replay that failed.",
          },
        ],
      },
      {
        type: "prose",
        text: "The event failed a second time and your queue now says it was fixed. It will never be looked at again. That is the event being lost twice.",
      },
    ],
  },
  {
    kind: "debug",
    id: "debug-it",
    title: "Work out why",
    content: [
      {
        type: "prose",
        text: "A different, very common symptom: the recovery flow stops at Fetch Pending DLQ Event and returns nothing at all.",
      },
      {
        type: "actions",
        items: [
          {
            text: "Query the table before changing the workflow.",
            code: {
              language: "sql",
              code: "select id, event_id, status from dlq_events order by id desc;",
            },
          },
          {
            text: "Compare the row's actual status against the filter.",
            expect: "The row is already recovered, and the filter asks for pending.",
          },
        ],
      },
      {
        type: "callout",
        tone: "gotcha",
        title: "Empty results usually mean the filter is right",
        text: "No output is not an n8n error. When a lookup finds nothing, inspect the filters and the current database state before touching the workflow — here, the filter correctly refused to replay something already recovered.",
      },
    ],
  },
  {
    kind: "challenge",
    id: "challenge",
    title: "Challenge: recover one, fail one",
    hintCount: 4,
    testCaseId: "lab-08-failed-replay-stays-pending",
    caseName: "A replay that fails again leaves the event pending rather than falsely recovered",
    content: [
      {
        type: "prose",
        text: "With curl, send both challenge events to your Production URL so evt_dlq_challenge_001 and evt_dlq_challenge_002 each land in the queue. Recover the first with recovery_scenario success, and the second with failure.",
      },
      {
        type: "code",
        language: "json",
        code: [
          "{",
          '  "event_id": "evt_dlq_challenge_001",',
          '  "event_type": "lead.sync",',
          '  "scenario": "permanent_failure",',
          '  "max_attempts": 3,',
          '  "data": { "lead_id": "lead_302", "name": "Challenge Lead", "email": "challenge@example.com" }',
          "}",
        ].join("\n"),
        caption: "Send it again with event_id evt_dlq_challenge_002 for the second event.",
      },
      {
        type: "prose",
        text: "Paste the Keep DLQ Pending output from the SECOND recovery below.",
      },
    ],
    verification: [
      "both events reach the queue as pending",
      "evt_dlq_challenge_001 ends recovered, with recovered_at populated",
      "evt_dlq_challenge_002 stays pending, with recovered_at still null",
      "only the true branch of Recovery Successful? can mark anything recovered",
    ],
  },
  {
    kind: "recap",
    id: "recap",
    title: "What you just built",
    content: [
      {
        type: "prose",
        text: "Failed work no longer disappears. Events that exhaust their retries are preserved with their original payload, their error, their attempt count and their timestamps — and can be replayed once the problem is fixed.",
      },
      {
        type: "prose",
        text: "You also learned the rule that makes recovery trustworthy: only a verified success may mark something recovered. A failed replay is still failed work.",
      },
    ],
    bridge: [
      {
        type: "prose",
        text: "Your automation is now genuinely reliable. It validates, refuses duplicates, retries what can recover and preserves what cannot — and every decision comes from a rule you wrote yourself.",
      },
      {
        type: "prose",
        text: "That is about to change. The next two labs introduce AI: remarkably good at reading intent, and remarkably willing to return something you did not expect. Lab 09 makes an AI answer safe enough to act on.",
      },
    ],
  },
];
