import type { LessonChunk } from "../types";

/** Lab 10 — AI Guardrails & Human-in-the-Loop. Condensed from the lab README. */
export const LAB_10_CHUNKS: readonly LessonChunk[] = [
  {
    kind: "problem",
    id: "problem",
    title: "Keep risky actions under human control",
    content: [
      {
        type: "prose",
        text: "A customer writes in: \"Please cancel my account today.\" Your AI reads it, understands it perfectly, and recommends cancel_account with a confidence of 1.00.",
      },
      {
        type: "prose",
        text: "It is completely correct. That is what the customer asked for. Now: should your workflow just do it?",
      },
      {
        type: "prose",
        text: "The answer is no, and the reason has nothing to do with whether the AI was right. Route an inquiry to the wrong team and someone forwards an email. Cancel the wrong account and you are talking to a customer who is no longer a customer. The cost of a mistake is not evenly spread across your actions, so your automation should not treat them as if it were.",
      },
    ],
  },
  {
    kind: "concept",
    id: "concept",
    title: "Confidence is not permission",
    content: [
      {
        type: "prose",
        text: "What is it? A guardrail is a rule outside the model that decides what an AI recommendation is allowed to do on its own. Anything it does not allow waits for a human.",
      },
      {
        type: "prose",
        text: "What problem does it solve? Confidence tells you how sure the AI is. It says nothing about whether an action is safe to take without a person. Those are two different systems, and most AI automation only builds the first.",
      },
      {
        type: "prose",
        text: "How does this help a real business? Routine work happens instantly, risky work stops for a person, and every decision leaves a record.",
      },
      {
        type: "callout",
        tone: "gotcha",
        title: "Confidence is not permission",
        text: "Automatic execution needs all three: the action is on the allowed list, AND confidence is at least 0.85, AND the action is not restricted. The third looks redundant — until someone pastes an extra action into the wrong list at 5pm on a Friday.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-policy",
    title: "Build: write the policy down as data",
    whyThisMatters: [
      {
        type: "prose",
        text: "Who may auto-execute what is a business decision, not a technical one. Keeping it in configuration means changing it is editing a field, and a compliance question is answered by showing someone a node rather than a source file.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Create the approval table in the Supabase SQL Editor, so a held request outlives the run that created it.",
        code: {
          language: "sql",
          code: [
            "create table public.approval_requests (",
            "  id                 bigint generated by default as identity primary key,",
            "  request_id         text not null,",
            "  recommended_action text not null,",
            "  confidence         numeric not null,",
            "  reason             text,",
            "  status             text not null default 'pending',",
            "  human_decision     text,",
            "  created_at         timestamptz not null default now(),",
            "  decided_at         timestamptz",
            ");",
          ].join("\n"),
        },
      },
      {
        text: "Add a Webhook named Receive Service Request (POST, path aep-lab-10-guardrails, Respond: Using Respond to Webhook node), then an Edit Fields node named Prepare Guardrail Input with the request and the policy.",
        code: {
          language: "text",
          code: [
            "request_id                 String   {{ $json.body.request_id }}",
            "message                    String   {{ $json.body.message }}",
            "allowed_automatic_actions  String   send_to_sales,create_support_ticket,send_to_billing",
            "restricted_actions         String   issue_refund,cancel_account",
            "confidence_threshold       Number   0.85",
          ].join("\n"),
        },
      },
      {
        text: "Add a Basic LLM Chain named Gemini Guardrail Decision (Source for Prompt: Define below) with this prompt. Turn on Require Specific Output Format, attach a Structured Output Parser with this JSON schema, and attach a Google Gemini Chat Model with your Gemini credential.",
        code: [
          {
            caption: "Prompt",
            language: "text",
            code: [
              "You are an AI service-request decision assistant.",
              "",
              "Customer request:",
              "{{ $json.message }}",
              "",
              "Allowed automatic actions:",
              "{{ $json.allowed_automatic_actions }}",
              "",
              "Restricted actions:",
              "{{ $json.restricted_actions }}",
              "",
              "Choose the single best recommended action for the request.",
              "",
              "Possible actions:",
              "- send_to_sales",
              "- create_support_ticket",
              "- send_to_billing",
              "- issue_refund",
              "- cancel_account",
              "- manual_review",
              "",
              "Return:",
              "- recommended_action",
              "- confidence from 0 to 1",
              "- a short reason",
              "",
              "Important decision rules:",
              "",
              "- If the customer explicitly asks to cancel, close, terminate, or delete their account, recommend \"cancel_account\".",
              "- If the customer explicitly requests a refund, recommend \"issue_refund\".",
              "- If the request is about billing but does NOT explicitly ask for a refund, recommend \"send_to_billing\".",
              "- If the request is a technical/account-access problem, recommend \"create_support_ticket\".",
              "- If the request is about buying, pricing, plans, or speaking with sales, recommend \"send_to_sales\".",
              "- Use \"manual_review\" only when the intent is genuinely unclear.",
              "",
              "Do not replace restricted actions with safer alternatives.",
              "Your job is to recommend the action that best matches the user's request.",
              "The guardrail system will decide whether it can run automatically.",
            ].join("\n"),
          },
          {
            caption: "Structured Output Parser schema",
            language: "json",
            code: [
              "{",
              "  \"type\": \"object\",",
              "  \"properties\": {",
              "    \"recommended_action\": {",
              "      \"type\": \"string\",",
              "      \"enum\": [",
              "        \"send_to_sales\",",
              "        \"create_support_ticket\",",
              "        \"send_to_billing\",",
              "        \"issue_refund\",",
              "        \"cancel_account\",",
              "        \"manual_review\"",
              "      ]",
              "    },",
              "    \"confidence\": {",
              "      \"type\": \"number\",",
              "      \"minimum\": 0,",
              "      \"maximum\": 1",
              "    },",
              "    \"reason\": {",
              "      \"type\": \"string\"",
              "    }",
              "  },",
              "  \"required\": [",
              "    \"recommended_action\",",
              "    \"confidence\",",
              "    \"reason\"",
              "  ],",
              "  \"additionalProperties\": false",
              "}",
            ].join("\n"),
          },
        ],
        expect: "cancel_account for the cancellation request.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "The prompt explicitly tells Gemini not to soften a risky request into a safe one. That sounds backwards until you see why: if the model quietly turns cancel my account into create a support ticket, your guardrail never sees a restricted action, no human is asked, and the customer's real request is silently ignored. We want the honest recommendation. Authorisation is not the model's job.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-guardrail",
    title: "Build: the node that authorises",
    whyThisMatters: [
      {
        type: "prose",
        text: "Gemini recommends; this node authorises. Keeping them in separate nodes means the AI can never be the thing that grants its own permission.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Add a Code node named Apply Guardrails that reads the policy back from Prepare Guardrail Input and computes three separate checks.",
        code: {
          language: "javascript",
          code: [
            "const ai = $json.output;",
            "const input = $('Prepare Guardrail Input').item.json;",
            "",
            "const allowedAutomaticActions = input.allowed_automatic_actions",
            "  .split(',')",
            "  .map(action => action.trim());",
            "",
            "const restrictedActions = input.restricted_actions",
            "  .split(',')",
            "  .map(action => action.trim());",
            "",
            "const threshold = Number(input.confidence_threshold);",
            "",
            "const isAllowedAutomatic = allowedAutomaticActions.includes(",
            "  ai.recommended_action",
            ");",
            "",
            "const isRestricted = restrictedActions.includes(",
            "  ai.recommended_action",
            ");",
            "",
            "const highConfidence = ai.confidence >= threshold;",
            "",
            "const canAutoExecute =",
            "  isAllowedAutomatic &&",
            "  highConfidence &&",
            "  !isRestricted;",
            "",
            "let guardrailReason;",
            "",
            "if (isRestricted) {",
            "  guardrailReason = 'restricted_action';",
            "} else if (!highConfidence) {",
            "  guardrailReason = 'low_confidence';",
            "} else if (!isAllowedAutomatic) {",
            "  guardrailReason = 'not_allowed_automatically';",
            "} else {",
            "  guardrailReason = 'automatic_action_allowed';",
            "}",
            "",
            "return {",
            "  json: {",
            "    request_id: input.request_id,",
            "    recommended_action: ai.recommended_action,",
            "    confidence: ai.confidence,",
            "    reason: ai.reason,",
            "    is_allowed_automatic: isAllowedAutomatic,",
            "    is_restricted: isRestricted,",
            "    high_confidence: highConfidence,",
            "    can_auto_execute: canAutoExecute,",
            "    requires_approval: !canAutoExecute,",
            "    guardrail_reason: guardrailReason",
            "  }",
            "};",
          ].join("\n"),
        },
      },
      {
        text: "Add an IF named Can Auto Execute? with the Boolean condition {{ $json.can_auto_execute }} is true. On true, add an Edit Fields node named Execute Automatic Action with these fields.",
        code: {
          language: "text",
          code: [
            "success                    Boolean  true",
            "status                     String   auto_executed",
            "request_id                 String   {{ $json.request_id }}",
            "action                     String   {{ $json.recommended_action }}",
            "confidence                 Number   {{ $json.confidence }}",
            "requires_approval          Boolean  false",
            "decision_source            String   ai_guardrail",
          ].join("\n"),
        },
      },
      {
        text: "On false, add a Supabase node named Create Pending Approval (Create in approval_requests: request_id, recommended_action, confidence and reason from the item, status pending), then an Edit Fields node named Return Pending Approval with these fields.",
        code: {
          language: "text",
          code: [
            "success                    Boolean  true",
            "status                     String   pending_approval",
            "request_id                 String   {{ $json.request_id }}",
            "action                     String   {{ $json.recommended_action }}",
            "confidence                 Number   {{ $json.confidence }}",
            "requires_approval          Boolean  true",
            "decision_source            String   ai_guardrail",
          ].join("\n"),
        },
      },
      {
        text: "Connect both paths into one Respond to Webhook named Return Guardrail Decision, responding with the first incoming item and code 200.",
        expect: "The cancellation returns pending_approval.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "The three checks come back as separate booleans rather than one folded answer. When something routes unexpectedly you can see which rule decided it without adding a single log line.",
      },
      {
        type: "prose",
        text: "Holding a restricted action returns success: true. Stopping it is the system working, not failing — marking it a failure would teach every dashboard downstream to treat correct behaviour as an incident.",
      },
    ],
    teaches: [
      {
        subject: "code",
        name: "The guardrail rule",
        language: "javascript",
        code: "isAllowedAutomatic && highConfidence && !isRestricted",
        intent: "Decide whether an AI recommendation may run without a person.",
        inputs: "The AI's recommended action and confidence, plus the allowed list, restricted list and threshold from policy.",
        logic:
          "All three must hold. The action must be explicitly allowed, the model must be at least as confident as the threshold, and the action must not be restricted. Failing any one sends the request to a human.",
        output: "can_auto_execute, plus which individual check failed.",
        engineeringReason:
          "The restricted check is a second lock on the same door. It survives the day someone edits the allowed list by mistake, which is the day it actually matters.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-human",
    title: "Build: a person makes the call",
    whyThisMatters: [
      {
        type: "prose",
        text: "A pending row is sitting in Supabase and nothing will happen to it on its own. This is the other half of the business process.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Add a Webhook named Receive Human Decision (POST, path aep-lab-10-approval-decision, Respond: Using Respond to Webhook node), then an Edit Fields node named Prepare Human Decision.",
        code: {
          language: "text",
          code: [
            "approval_id                String   {{ $json.body.approval_id }}",
            "decision                   String   {{ $json.body.decision }}",
          ].join("\n"),
        },
      },
      {
        text: "Add a Supabase node named Fetch Pending Approval: Operation Get in approval_requests, with BOTH conditions id equals {{ $json.approval_id }} and status equals pending.",
      },
      {
        text: "Add an IF named Approve or Reject? with the String condition {{ $('Prepare Human Decision').item.json.decision }} is equal to approve.",
      },
      {
        text: "On true, Mark Approved (Update approval_requests where id equals {{ $json.id }}: status approved, human_decision approved, decided_at {{ $now }}) then Execute Approved Action. On false, Mark Rejected (the same update with rejected) then Return Rejected Decision. Connect both into a Respond to Webhook named Return Human Decision Result.",
        code: [
          {
            caption: "Execute Approved Action",
            language: "text",
            code: [
              "success                    Boolean  true",
              "status                     String   approved_and_executed",
              "approval_id                Number   {{ $json.id }}",
              "request_id                 String   {{ $json.request_id }}",
              "action                     String   {{ $json.recommended_action }}",
              "human_decision             String   approve",
              "decision_source            String   ai_guardrail",
            ].join("\n"),
          },
          {
            caption: "Return Rejected Decision",
            language: "text",
            code: [
              "success                    Boolean  true",
              "status                     String   rejected",
              "approval_id                Number   {{ $json.id }}",
              "request_id                 String   {{ $json.request_id }}",
              "action                     String   {{ $json.recommended_action }}",
              "human_decision             String   rejected",
              "decision_source            String   ai_guardrail",
            ].join("\n"),
          },
        ],
        expect: "Approving returns approved_and_executed.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "callout",
        tone: "note",
        title: "status = pending is the quiet hero",
        text: "Without that filter someone could approve the same cancellation three times and it would run three times. With it, the second attempt finds no row. You met this idea in Lab 07 as idempotency — state in the database decides what may still happen, not the caller's good intentions.",
      },
      {
        type: "prose",
        text: "decided_at is what turns a row into an audit trail. Who approved this, and when, is the first question asked after any expensive mistake.",
      },
    ],
  },
  {
    kind: "predict",
    id: "predict",
    title: "Before you run it",
    content: [
      {
        type: "prose",
        text: "Gemini will recommend cancel_account for the cancellation request, and it will be very sure — confidence around 1.00.",
      },
    ],
    prompt: "Does that confidence earn it permission to run automatically?",
    reveal: [
      {
        type: "prose",
        text: "No. cancel_account is restricted, so it is held for approval regardless of how confident the model is. There is no value of confidence that would have let it through.",
      },
      {
        type: "prose",
        text: "That is the sentence the whole lab exists to produce: the AI was completely right, and it still does not get to do it.",
      },
    ],
  },
  {
    kind: "test",
    id: "success-test",
    title: "Prove it",
    mode: "send-test",
    testCaseId: "lab-10-restricted-held",
    payload: { request_id: "req_guard_restricted_001", message: "Please cancel my account today." },
    expected: "Held as pending approval, with a human required — not executed.",
    caseName: "A confident request to cancel an account waits for a human instead of executing",
    content: [
      {
        type: "prose",
        text: "Publish your workflow in n8n (older versions call this switching it to Active), save its Production URL below, then send the test. AEP posts this lab's sample request to your own n8n and checks what your workflow answers. Each send creates a pending row in approval_requests — note its id in Supabase, you will need it for the challenge.",
      },
    ],
  },
  {
    kind: "break-it",
    id: "break-it",
    title: "Now break it on purpose",
    content: [
      {
        type: "prose",
        text: "A tired engineer simplifies the guardrail. Confidence is basically a quality score, right? High confidence means the AI knows what it is doing.",
      },
      {
        type: "actions",
        items: [
          {
            text: "In Apply Guardrails, temporarily replace the rule with confidence alone.",
            code: { language: "javascript", code: "const canAutoExecute = highConfidence;" },
          },
          {
            text: "Add a Code node named Simulate Restricted Decision, wire it in place of Gemini between Prepare Guardrail Input and Apply Guardrails — it returns cancel_account at 0.95 — and send the cancellation request again.",
            code: {
              language: "javascript",
              code: [
                "return {",
                "  json: {",
                "    output: {",
                "      recommended_action: 'cancel_account',",
                "      confidence: 0.95,",
                "      reason: 'The customer explicitly asked to cancel their account.'",
                "    }",
                "  }",
                "};",
              ].join("\n"),
            },
            expect: "status: auto_executed.",
          },
        ],
      },
      {
        type: "prose",
        text: "No error. No warning. A green execution, and your workflow just cancelled an account on its own authority. Every dashboard you own would report this run as a success.",
      },
    ],
  },
  {
    kind: "debug",
    id: "debug-it",
    title: "Work out why",
    content: [
      {
        type: "actions",
        items: [
          {
            text: "Open Apply Guardrails' output and read is_restricted.",
            expect: "true. It was calculated correctly.",
          },
          {
            text: "So the detection works. Find where between detection and decision the signal was dropped.",
          },
          {
            text: "Restore the three-part rule, rewire Gemini, and rerun the cancellation.",
            expect: "pending_approval again.",
          },
        ],
      },
      {
        type: "callout",
        tone: "gotcha",
        title: "A safety signal nothing reads is decoration",
        text: "The restricted check was still computed and visible in the output. Nothing consumed it. A workflow that runs perfectly can still do something it was never permitted to do — correctness and compliance are different tests.",
      },
      {
        type: "prose",
        text: "Make sure the correct rule is what you leave in place. The weakened version is a teaching exercise, not a save point.",
      },
    ],
  },
  {
    kind: "challenge",
    id: "challenge",
    title: "Challenge: the full authorisation lifecycle",
    hintCount: 4,
    testCaseId: "lab-10-human-approved",
    caseName: "A held request runs only after a person approves it",
    content: [
      {
        type: "prose",
        text: "Prove each path against your Production URL: one safe action runs automatically, one restricted action is held, and one allowed-but-uncertain action is held too.",
      },
      {
        type: "code",
        language: "text",
        code: [
          "safe          {\"request_id\": \"req_guard_challenge_001\", \"message\": \"I'd like to know your pricing and speak with someone about your plans.\"}",
          "restricted    {\"request_id\": \"req_guard_challenge_002\", \"message\": \"Please cancel my account today.\"}",
          "uncertain     recommended_action send_to_sales at confidence 0.60 (req_guard_challenge_003)",
          "",
          "decide        POST to your aep-lab-10-approval-decision Production URL:",
          "              {\"approval_id\": <the id of a pending row>, \"decision\": \"approve\"}   or  \"reject\"",
        ].join("\n"),
      },
      {
        type: "prose",
        text: "Approve one pending request, reject another, then send the same approval a second time — it finds no pending row, so nothing runs and the response is empty. Paste the response to your FIRST approval below.",
      },
      {
        type: "callout",
        tone: "warning",
        title: "One scenario is not for Gemini",
        text: "The low-confidence case specifies a confidence value directly, and you cannot ask a model to be unsure on demand. You built something in this lab for exactly that.",
      },
    ],
    verification: [
      "a safe action executes automatically with no human involved",
      "a restricted action and a low-confidence action both become pending rows",
      "approving runs the action; rejecting runs nothing",
      "both decisions persist status, human_decision and decided_at together",
      "re-sending a decision for an already-decided request finds nothing",
    ],
  },
  {
    kind: "recap",
    id: "recap",
    title: "What you just built",
    content: [
      {
        type: "prose",
        text: "An authorisation layer between an AI's recommendation and any real action, plus the human approval loop for everything the machine is not allowed to do alone.",
      },
      {
        type: "prose",
        text: "AI recommends; guardrails authorise; humans own the risky calls. Keeping those three in separate nodes is what makes the boundary real rather than aspirational — and you proved it by breaking it and watching a confident, silent, technically perfect policy violation go through.",
      },
    ],
    bridge: [
      {
        type: "prose",
        text: "Look at what you can now do: validate and normalise a request, refuse to process it twice, retry what is worth retrying, keep failed work recoverable, force AI output into a shape you can trust, and authorise what AI may do.",
      },
      {
        type: "prose",
        text: "They are still ten separate workflows. Real systems do not get to be tidy like that. The Capstone is one system where all of it runs together — and where the interesting problems live in how the pieces interact.",
      },
    ],
  },
];
