import type { LessonChunk } from "../types";

/** Lab 07 — Idempotency & Duplicate Protection. Condensed from the lab README. */
export const LAB_07_CHUNKS: readonly LessonChunk[] = [
  {
    kind: "problem",
    id: "problem",
    title: "The problem",
    content: [
      {
        type: "prose",
        text: "A CRM sends you a webhook: new lead created. Your workflow handles it perfectly.",
      },
      {
        type: "prose",
        text: "Then the CRM's own retry logic fires, because it never saw your response in time. The same event arrives again, and your workflow handles it perfectly. Again. The customer now has two welcome emails and two records with their name on them.",
      },
      {
        type: "prose",
        text: "Every serious webhook provider retries — Stripe, Shopify, your CRM. They would rather deliver an event twice than zero times, which is the right call on their side and becomes your problem. A duplicate log line costs nothing. A duplicate refund costs a customer.",
      },
    ],
  },
  {
    kind: "concept",
    id: "concept",
    title: "The concept",
    content: [
      {
        type: "prose",
        text: "What is it? Idempotency means the same event can arrive many times while the business action happens exactly once.",
      },
      {
        type: "prose",
        text: "What problem does it solve? Retries, timeouts and at-least-once delivery all produce duplicates. Without protection each one repeats its side effect — another charge, another email, another record.",
      },
      {
        type: "prose",
        text: "How does this help a real business? Payments, orders, bookings and notifications stay single no matter how many times the sender retries.",
      },
      {
        type: "callout",
        tone: "note",
        title: "Why this lab needs a database",
        text: "\"Have I seen this event before?\" is a question no workflow can answer from memory. An execution forgets everything the moment it ends, so the answer has to be written somewhere that outlives it.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-memory",
    title: "Build: give the workflow a memory",
    whyThisMatters: [
      {
        type: "prose",
        text: "The protection lives in the database, not in an IF node. A table whose primary key is the event id physically cannot hold the same event twice — which is what makes it safe even when two copies arrive in the same instant.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Open your Supabase project's SQL Editor and create the table that remembers events.",
        code: {
          language: "sql",
          code: [
            "create table if not exists processed_events (",
            "  event_id     text primary key,",
            "  event_type   text,",
            "  status       text not null default 'reserved',",
            "  created_at   timestamptz not null default now(),",
            "  processed_at timestamptz",
            ");",
          ].join("\n"),
        },
      },
      {
        text: "Create the table that stands in for the real business action. It deliberately has no unique constraint.",
        code: {
          language: "sql",
          code: [
            "create table if not exists lab07_business_actions (",
            "  id          bigint generated by default as identity primary key,",
            "  event_id    text not null,",
            "  action_type text not null,",
            "  lead_id     text,",
            "  created_at  timestamptz not null default now()",
            ");",
          ].join("\n"),
        },
      },
      {
        text: "In n8n, add a Supabase credential if you do not already have one: Host is your project URL, and the secret is the secret API key from your Supabase project's API settings. It stays inside n8n.",
        expect: "Both tables visible in the Supabase table editor.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "event_id is the column that matters: as the primary key, a second insert of the same id is rejected by the database itself.",
      },
      {
        type: "prose",
        text: "lab07_business_actions has no constraint on purpose. It is the thing you are protecting, so if your workflow's protection fails, duplicates will visibly pile up here — which is exactly how you will prove it works.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-lookup",
    title: "Build: recognise an event you have seen",
    whyThisMatters: [
      {
        type: "prose",
        text: "Idempotency needs a stable identity. If the same event can produce two different keys, every duplicate looks brand new and all of this protection is decoration.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Add a Webhook node named Receive External Event: POST, path aep-lab-07-event, Respond: Using Respond to Webhook node.",
      },
      {
        text: "Add a Code node named Extract Event Identity that uses the provider's id when there is one, and builds a fallback when there is not.",
        code: {
          language: "javascript",
          code: [
            "const body = $json.body;",
            "const eventId = body.event_id ?? `${body.event_type}:${body.data?.lead_id}`;",
            "return { json: { event_id: eventId, event_type: body.event_type, data: body.data } };",
          ].join("\n"),
        },
      },
      {
        text: "Add a Supabase node named Check Processed Event: Operation Get, table processed_events, condition event_id equals {{ $json.event_id }}. In its Settings, turn on Always Output Data.",
      },
      {
        text: "Add an IF named Already Seen? with the Boolean condition {{ Object.keys($json).length > 0 }} is true. On true, add a Respond to Webhook named Return Duplicate Ignored: Respond With JSON, Response Code 200, and this Response Body in Expression mode.",
        code: {
          language: "json",
          code: [
            "{",
            "  \"success\": true,",
            "  \"duplicate\": true,",
            "  \"message\": \"Duplicate event ignored\",",
            "  \"event_id\": \"{{ $('Extract Event Identity').item.json.event_id }}\"",
            "}",
          ].join("\n"),
        },
      },
    ],
    whyWereDoingThis: [
      {
        type: "callout",
        tone: "gotcha",
        title: "An empty lookup is {} — not an error",
        text: "When Supabase finds nothing, n8n passes on an empty object. Checking $json.event_id then reads undefined; checking whether the object has any keys is what reliably tells you a row came back.",
      },
      {
        type: "prose",
        text: "A duplicate is answered with success: true. The desired outcome already happened, so a second delivery is not a failure — reporting it as one would teach every monitor downstream to page someone for correct behaviour.",
      },
    ],
    teaches: [
      {
        subject: "node",
        name: "Supabase",
        what: "Reads and writes rows in your Supabase database from inside a workflow.",
        whyHere:
          "An execution forgets everything when it ends. To know whether an event was already handled, the answer has to live somewhere every future run can see.",
        businessReason:
          "Shared, durable state is what lets separate runs — including two running in the same second — agree on what has already happened.",
        analogy: "The workflow's long-term memory.",
      },
      {
        subject: "code",
        name: "A fallback idempotency key",
        language: "javascript",
        code: "body.event_id ?? `${body.event_type}:${body.data?.lead_id}`",
        intent: "Give every event a stable identity, even when the sender does not supply one.",
        inputs: "The provider's event_id if present; otherwise the event type and the lead it concerns.",
        logic:
          "?? uses the right-hand side only when event_id is null or undefined. The fallback joins type and lead id, so the same lead being created twice produces the same key both times.",
        output: "evt_504 from a provider, or lead.created:lead_203 when none was sent.",
        engineeringReason:
          "A generated key is only safe if its parts truly identify one business event. If the same lead can legitimately be created twice, this key would wrongly block the second — so provider ids are always preferred.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-reserve",
    title: "Build: reserve first, act second",
    whyThisMatters: [
      {
        type: "prose",
        text: "Two copies of an event can arrive close enough together that both lookups find nothing. The order you do the next two things in decides whether you get one business action or two.",
      },
    ],
    content: [],
    actions: [
      {
        text: "On false, add a Supabase node named Reserve Event: Operation Create in processed_events, with event_id and event_type from Extract Event Identity and status reserved. In its Settings, set On Error to Continue.",
      },
      {
        text: "Add an IF named Reservation Succeeded? with the Boolean condition {{ !$json.error }} is true, so it passes only when the insert returned no error.",
      },
      {
        text: "On true, add Execute Business Action (Create in lab07_business_actions: event_id, action_type create_lead, lead_id), then Mark Processed (Update processed_events where event_id matches: status processed, processed_at {{ $now }}).",
      },
      {
        text: "Finish with a Respond to Webhook named Return Processed Success with this Response Body, and send the false branch of Reservation Succeeded? to Return Duplicate Ignored too.",
        code: {
          language: "json",
          code: [
            "{",
            "  \"success\": true,",
            "  \"duplicate\": false,",
            "  \"message\": \"Event processed successfully\",",
            "  \"event_id\": \"{{ $json.event_id }}\",",
            "  \"status\": \"{{ $json.status }}\"",
            "}",
          ].join("\n"),
        },
        expect: "A first delivery returns duplicate: false.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "Act-then-save leaves a window where both copies act before either saves. Reserve-then-act closes it: only the request whose insert succeeds may continue, and the database's primary key decides which one that is.",
      },
      {
        type: "callout",
        tone: "note",
        title: "Two layers, two jobs",
        text: "The lookup handles the ordinary duplicate cleanly. The reservation's unique key catches the race the lookup cannot see. Remove either and a case slips through.",
      },
    ],
  },
  {
    kind: "predict",
    id: "predict",
    title: "Before you run it",
    content: [
      {
        type: "prose",
        text: "You are about to send the new-event sample twice, identically.",
      },
    ],
    prompt:
      "How many rows will lab07_business_actions hold for evt_504 afterwards, and what does the second response say?",
    reveal: [
      {
        type: "prose",
        text: "One row. The second delivery finds evt_504 in processed_events, answers duplicate: true, and never reaches Reserve Event, Execute Business Action or Mark Processed.",
      },
      {
        type: "code",
        language: "sql",
        code: "select count(*) from lab07_business_actions where event_id = 'evt_504';",
        caption: "Two deliveries in, one business action out.",
      },
    ],
  },
  {
    kind: "test",
    id: "success-test",
    title: "Prove it",
    mode: "send-test",
    testCaseId: "lab-07-duplicate-ignored",
    payload: { event_id: "evt_504", event_type: "lead.created", data: { lead_id: "lead_104", name: "New Event", email: "new@example.com" } },
    expected: "The second delivery comes back as a duplicate, deliberately ignored.",
    deliveries: 2,
    caseName: "The same event delivered twice performs its business action only once",
    content: [
      {
        type: "prose",
        text: "Publish your workflow in n8n (older versions call this switching it to Active), save its Production URL below, then send the test. AEP posts this lab's sample request to your own n8n and checks what your workflow answers. AEP sends the same event twice and judges the second answer — the first proves nothing, because it succeeds whether protection exists or not.",
      },
    ],
  },
  {
    kind: "break-it",
    id: "break-it",
    title: "Now break it on purpose",
    content: [
      {
        type: "actions",
        items: [
          {
            text: "Temporarily connect Extract Event Identity straight to Execute Business Action, bypassing both protection layers.",
          },
          {
            text: "Send an event with an event_id you have never used — for example evt_break_yourname_001 — twice.",
          },
          {
            text: "Count its business actions.",
            code: {
              language: "sql",
              code: "select count(*) from lab07_business_actions where event_id = 'evt_break_yourname_001';",
            },
            expect: "2, from a single event.",
          },
        ],
      },
      {
        type: "prose",
        text: "Both deliveries succeeded. Both were green. Your customer was charged twice.",
      },
    ],
  },
  {
    kind: "debug",
    id: "debug-it",
    title: "Work out why",
    content: [
      {
        type: "actions",
        items: [
          {
            text: "Was the first delivery ever written to processed_events? Without that row there is nothing for the second one to find.",
          },
          {
            text: "Did both deliveries produce the same event_id? Compare Extract Event Identity's output on each.",
          },
          {
            text: "Restore the protected path and send another new event_id twice.",
            expect: "One business action.",
          },
        ],
      },
      {
        type: "callout",
        tone: "gotcha",
        title: "A lookup alone is not enough",
        text: "Two requests arriving together can both look, both find nothing, and both proceed. That is a race condition, and application logic cannot close it on its own — the database's unique key during reservation is the final safety net.",
      },
    ],
  },
  {
    kind: "challenge",
    id: "challenge",
    title: "Challenge: three deliveries, two events",
    hintCount: 4,
    testCaseId: "lab-07-new-event-after-duplicate",
    caseName: "A new event after a duplicate is still processed, not wrongly blocked",
    content: [
      {
        type: "prose",
        text: "Send three deliveries to your Production URL: a new event, the same event again, then a second new event. Use event ids you have never sent — evt_challenge_yourname_001 and _002 — because an id your workflow has already seen can never be new again, which is the whole point. Predict each response before you send it.",
      },
      {
        type: "code",
        language: "json",
        code: [
            "{",
            "  \"event_id\": \"evt_challenge_yourname_001\",",
            "  \"event_type\": \"lead.created\",",
            "  \"data\": { \"lead_id\": \"lead_201\", \"name\": \"Casey Wong\", \"email\": \"casey@example.com\" }",
            "}",
        ].join("\n"),
      },
      {
        type: "prose",
        text: "Send all three in order, then paste the response to the THIRD delivery below.",
      },
      {
        type: "callout",
        tone: "warning",
        title: "Protection can be too eager",
        text: "A workflow that blocks everything after its first duplicate would pass a duplicate test perfectly. A genuinely new event is what proves it is recognising duplicates rather than refusing work.",
      },
    ],
    verification: [
      "the first event is processed on its first delivery",
      "its second delivery is ignored as a duplicate",
      "the second new event is processed normally afterwards",
      "each event has exactly one row in lab07_business_actions",
    ],
  },
  {
    kind: "recap",
    id: "recap",
    title: "What you just built",
    content: [
      {
        type: "prose",
        text: "The same event can now arrive any number of times and its business action runs exactly once. The database enforces that, rather than trusting your logic to.",
      },
      {
        type: "prose",
        text: "You gave events a stable identity, reserved before acting, handled the empty-lookup quirk, and saw why a lookup and a unique constraint are two different defences against two different failures.",
      },
    ],
    bridge: [
      {
        type: "prose",
        text: "But look at what happens when an event is genuinely new and genuinely fails — permanently. Retries run out, the workflow stops, and there is now no record the event ever existed.",
      },
      {
        type: "prose",
        text: "You have controlled duplicates. You have not yet controlled loss. Lab 08 makes sure failed work survives.",
      },
    ],
  },
];
