import type { LessonChunk } from "../types";

/** Lab 08 — Dead Letter Queue & Failure Recovery. Condensed from the lab README. */
export const LAB_08_CHUNKS: readonly LessonChunk[] = [
  {
    kind: "problem",
    id: "problem",
    title: "The problem",
    content: [
      {
        type: "prose",
        text: "Three retries. Three failures. The downstream service is not coming back this afternoon.",
      },
      {
        type: "prose",
        text: "Your workflow does the only thing it knows how to do: it stops. And the customer's order — the thing this automation existed to handle — is now gone. Not delayed. Gone.",
      },
      {
        type: "prose",
        text: "Retries handle failures that end. Some do not: a service down for hours, a credential that expired overnight. When retries run out the work has to go somewhere, or you find out it was lost when a customer asks why nothing happened.",
      },
    ],
  },
  {
    kind: "concept",
    id: "concept",
    title: "The concept",
    content: [
      {
        type: "prose",
        text: "What is it? A Dead Letter Queue is a safe place for events that normal processing could not recover. The event is not deleted — it is preserved so someone can inspect it or replay it later.",
      },
      {
        type: "prose",
        text: "What problem does it solve? After retries are exhausted, a workflow without a DLQ has two options: stop and lose the work, or loop forever. A DLQ adds a third.",
      },
      {
        type: "prose",
        text: "How does this help a real business? Orders, payments and CRM syncs survive outages. The difference between a fragile system and a resilient one is not that the resilient one never fails — it is that failed work is still there in the morning.",
      },
      {
        type: "diagram",
        ascii: [
          "Event -> Process -> fail -> retry -> fail -> retry -> fail",
          "                                                     |",
          "                                          retries exhausted",
          "                                                     |",
          "                                               Save to DLQ",
          "",
          "Later:  Fetch pending -> Replay -> succeeded? -> mark recovered",
          "                                          \\-> stays pending",
        ].join("\n"),
        alt: "An event fails and retries until attempts are exhausted, then is saved to the dead letter queue. Later a recovery flow fetches it, replays it, and marks it recovered only if the replay succeeded; otherwise it stays pending.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-retry",
    title: "Build: process, and retry until the limit",
    whyThisMatters: [
      {
        type: "prose",
        text: "A DLQ is what happens after normal recovery has failed. So the retries come first: an event that would have succeeded on attempt three must never reach the queue.",
      },
    ],
    content: [],
    actions: [
      {
        text: "Create the queue table in the Supabase SQL Editor.",
        code: {
          language: "sql",
          code: [
            "create table if not exists dlq_events (",
            "  id               bigint generated by default as identity primary key,",
            "  event_id         text not null,",
            "  event_type       text not null,",
            "  original_payload jsonb not null,",
            "  error_message    text not null,",
            "  retry_count      integer not null default 0,",
            "  first_failed_at  timestamptz not null default now(),",
            "  last_failed_at   timestamptz not null default now(),",
            "  status           text not null default 'pending',",
            "  recovered_at     timestamptz",
            ");",
          ].join("\n"),
        },
      },
      {
        text: "Add a Webhook named Receive Service Event on path aep-lab-08-dlq, then Prepare Processing Attempt and the Simulate Downstream Processing node from the lab's workflow export.",
      },
      {
        text: "Add an IF named Processing Successful?, and on FALSE an IF named Retry Allowed? checking attempt is less than max_attempts.",
      },
      {
        text: "On TRUE add Increase Retry Count and loop it back into Simulate Downstream Processing.",
        expect: "A permanent failure tries three times, then Retry Allowed? goes false.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "original_payload is the most important column in the table. Knowing an event failed is not enough to recover it; you need the event itself, because the sender may no longer have it.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-queue",
    title: "Build: preserve the failure",
    whyThisMatters: [
      {
        type: "prose",
        text: "When Retry Allowed? goes false, the workflow has given up — for now. What it saves in the next few seconds decides whether anyone can ever recover this event.",
      },
    ],
    content: [],
    actions: [
      {
        text: "On FALSE add a Code node named Build DLQ Record that captures everything a recovery would need.",
        code: {
          language: "javascript",
          code: [
            "return { json: {",
            "  event_id: $json.event_id,",
            "  original_payload: $json.original_payload,",
            "  error_message: $json.processing_result.error_message,",
            "  retry_count: $json.attempt,",
            "  status: 'pending'",
            "} };",
          ].join("\n"),
        },
      },
      {
        text: "Add a Supabase node named Save to DLQ that creates the row in dlq_events.",
      },
      {
        text: "Add a Respond to Webhook named Return Queued for Recovery.",
        expect: "success: false and queued_for_recovery: true in the same response.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "success: false with queued_for_recovery: true says two honest things at once: processing did not succeed, and the event was not lost. Collapsing them into one boolean would hide whichever one the caller needed.",
      },
    ],
    teaches: [
      {
        subject: "code",
        name: "Building the dead letter record",
        language: "javascript",
        code: "retry_count: $json.attempt,\noriginal_payload: $json.original_payload,\nstatus: 'pending'",
        intent: "Capture everything someone would need to understand and replay this failure later.",
        inputs: "The processing state at the moment retries were exhausted: the event, its original payload, the last error and the attempt count.",
        logic:
          "It selects the recovery-relevant fields rather than dumping the whole working state, and stamps the record pending so a recovery flow can find it.",
        output: "One clean row: what failed, why, after how many attempts, and the payload needed to try again.",
        engineeringReason:
          "A DLQ that stores only an error message tells you something failed and leaves you unable to fix it. The payload is what turns a failure report into recoverable work.",
      },
    ],
  },
  {
    kind: "guided-build",
    id: "build-recovery",
    title: "Build: replay it later — honestly",
    whyThisMatters: [
      {
        type: "prose",
        text: "Saving failures is half the job. The other half is getting them back out, and marking them recovered only when they actually were.",
      },
    ],
    content: [],
    actions: [
      {
        text: "In a separate flow, add a Manual Trigger named Start DLQ Recovery and a Set Recovery Config node with dlq_id and recovery_scenario.",
        expect: "Use the id of YOUR row — Postgres assigns ids in insert order.",
      },
      {
        text: "Add Fetch Pending DLQ Event, filtering on BOTH id and status = pending.",
      },
      {
        text: "Add Prepare Replay Payload and Simulate Recovery Processing, then an IF named Recovery Successful?",
      },
      {
        text: "On TRUE, Mark DLQ Recovered (status recovered, recovered_at now). On FALSE, a Code node named Keep DLQ Pending.",
        expect: "A failed replay leaves the row pending.",
      },
    ],
    whyWereDoingThis: [
      {
        type: "prose",
        text: "The status = pending filter is doing real work: an already-recovered event cannot be fetched and replayed again.",
      },
    ],
  },
  {
    kind: "predict",
    id: "predict",
    title: "Before you run it",
    content: [
      {
        type: "prose",
        text: "You have two samples: one that fails permanently, and one that fails twice and succeeds on the third attempt.",
      },
    ],
    prompt: "Which of them should end up in dlq_events?",
    reveal: [
      {
        type: "prose",
        text: "Only the permanent failure. The eventual-success event recovers inside its retries and finishes normally, so it has no business in a dead letter queue. A DLQ full of events that actually succeeded is noise that buries the ones that did not.",
      },
    ],
  },
  {
    kind: "test",
    id: "success-test",
    title: "Prove it",
    mode: "send-test",
    testCaseId: "lab-08-queued-for-recovery",
    payload: { event_id: "evt_dlq_001", event_type: "lead.sync", scenario: "permanent_failure", max_attempts: 3, data: { lead_id: "lead_301", name: "DLQ Test Lead", email: "dlq@example.com" } },
    expected: "success is false, but the event is queued for recovery after all 3 attempts — not lost.",
    caseName: "An event that fails permanently is preserved for recovery instead of being lost",
    content: [
      {
        type: "prose",
        text: "Activate your workflow, save its Production URL below, then send the test. AEP posts this lab's sample request to your own n8n and checks what your workflow answers. This event fails on every attempt, by design.",
      },
    ],
  },
  {
    kind: "break-it",
    id: "break-it",
    title: "Now break it on purpose",
    content: [
      {
        type: "actions",
        items: [
          {
            text: "In the recovery flow, bypass Recovery Successful? by connecting Simulate Recovery Processing straight to Mark DLQ Recovered.",
          },
          {
            text: "Run recovery on a pending row with recovery_scenario set to failure.",
          },
          {
            text: "Look at the row in dlq_events.",
            expect: "status recovered, recovered_at populated — for a replay that failed.",
          },
        ],
      },
      {
        type: "prose",
        text: "The event failed a second time and your queue now says it was fixed. It will never be looked at again. That is the event being lost twice.",
      },
    ],
  },
  {
    kind: "debug",
    id: "debug-it",
    title: "Work out why",
    content: [
      {
        type: "prose",
        text: "A different, very common symptom: the recovery flow stops at Fetch Pending DLQ Event and returns nothing at all.",
      },
      {
        type: "actions",
        items: [
          {
            text: "Query the table before changing the workflow.",
            code: {
              language: "sql",
              code: "select id, event_id, status from dlq_events order by id desc;",
            },
          },
          {
            text: "Compare the row's actual status against the filter.",
            expect: "The row is already recovered, and the filter asks for pending.",
          },
        ],
      },
      {
        type: "callout",
        tone: "gotcha",
        title: "Empty results usually mean the filter is right",
        text: "No output is not an n8n error. When a lookup finds nothing, inspect the filters and the current database state before touching the workflow — here, the filter correctly refused to replay something already recovered.",
      },
    ],
  },
  {
    kind: "challenge",
    id: "challenge",
    title: "Challenge: recover one, fail one",
    hintCount: 4,
    testCaseId: "lab-08-failed-replay-stays-pending",
    caseName: "A replay that fails again leaves the event pending rather than falsely recovered",
    content: [
      {
        type: "prose",
        text: "Send both challenge events so evt_dlq_challenge_001 and evt_dlq_challenge_002 each land in the queue. Recover the first with recovery_scenario success, and the second with failure.",
      },
      {
        type: "prose",
        text: "Paste the Keep DLQ Pending output from the SECOND recovery below.",
      },
    ],
    verification: [
      "both events reach the queue as pending",
      "evt_dlq_challenge_001 ends recovered, with recovered_at populated",
      "evt_dlq_challenge_002 stays pending, with recovered_at still null",
      "only the true branch of Recovery Successful? can mark anything recovered",
    ],
  },
  {
    kind: "recap",
    id: "recap",
    title: "What you just built",
    content: [
      {
        type: "prose",
        text: "Failed work no longer disappears. Events that exhaust their retries are preserved with their original payload, their error, their attempt count and their timestamps — and can be replayed once the problem is fixed.",
      },
      {
        type: "prose",
        text: "You also learned the rule that makes recovery trustworthy: only a verified success may mark something recovered. A failed replay is still failed work.",
      },
    ],
    bridge: [
      {
        type: "prose",
        text: "Your automation is now genuinely reliable. It validates, refuses duplicates, retries what can recover and preserves what cannot — and every decision comes from a rule you wrote yourself.",
      },
      {
        type: "prose",
        text: "That is about to change. The next two labs introduce AI: remarkably good at reading intent, and remarkably willing to return something you did not expect. Lab 09 makes an AI answer safe enough to act on.",
      },
    ],
  },
];
